Repository python-discord/sir-lancebot, pull requests merged in 2020-05, with the labels that each got.

#410 Set ayncio event loop to Selector on windows.
  bot/__init__.py
Labels: area: backend, priority: 1 - high, status: needs review, type: bug

#407 Show bot prefix in rich presence
  bot/bot.py
Labels: area: frontend, priority: 2 - normal, status: needs review, type: feature

#406 Fixed Prefix and Website
  bot/exts/evergreen/snakes/snakes_cog.py
Labels: area: frontend, status: needs review, type: bug

#403 Handle staff users and DMs in the halloweenify cog
  bot/exts/halloween/halloweenify.py
Labels: area: frontend, priority: 2 - normal, season: halloween, status: needs review, type: bug

#401 handle disabled DMs when starting Minesweeper
  bot/exts/evergreen/minesweeper.py
Labels: area: frontend, season: evergreen, status: needs review, type: bug

#413 Encoding bug fix
  bot/exts/christmas/adventofcode.py
  bot/exts/easter/april_fools_vids.py
  bot/exts/easter/egg_decorating.py
  bot/exts/evergreen/branding.py
  bot/exts/evergreen/magic_8ball.py
  bot/exts/evergreen/recommend_game.py
  bot/exts/evergreen/snakes/converter.py
  bot/exts/evergreen/speedrun.py
  bot/exts/evergreen/trivia_quiz.py
  bot/exts/halloween/candy_collection.py
  bot/exts/halloween/hacktoberstats.py
  bot/exts/halloween/halloween_facts.py
  bot/exts/halloween/halloweenify.py
  bot/exts/halloween/monstersurvey.py
  bot/exts/halloween/spookyrating.py
  bot/exts/pride/drag_queen_name.py
  bot/exts/pride/pride_anthem.py
  bot/exts/pride/pride_facts.py
  bot/exts/valentines/be_my_valentine.py
  bot/exts/valentines/lovecalculator.py
  bot/exts/valentines/myvalenstate.py
  bot/exts/valentines/valentine_zodiac.py
  bot/exts/valentines/whoisvalentine.py
  bot/utils/persist.py
Labels: area: backend, priority: 1 - high, status: needs review, type: bug
