Repository python-discord/sir-lancebot, pull requests merged in 2020-11, with the labels that each got.

#515 Remove persistence requirements from Seasonalbot
  bot/exts/evergreen/branding.py
  bot/exts/halloween/candy_collection.py
  bot/exts/halloween/hacktoberstats.py
  bot/exts/halloween/monstersurvey.py
  bot/utils/persist.py
Labels: s: waiting for author

#517 Remove DockerHub from GitHub Actions
  .github/workflows/lint-build-deploy.yaml
Labels: area: CI, needs 1 approval, priority: 0 - critical

#520 Fix flake8 check in CI and separate Lint and Build jobs into separate workflows
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
  bot/exts/evergreen/branding.py
  bot/exts/halloween/candy_collection.py
  bot/exts/halloween/hacktoberstats.py
Labels: area: CI, needs 1 approval, priority: 1 - high, type: bug

#524 feature/add wonder twins command
  bot/exts/evergreen/wonder_twins.py
  bot/resources/evergreen/wonder_twins.yaml
Labels: season: evergreen, type: feature

#532 Add check for core dev approvals on pull requests
  .github/CODEOWNERS
  .github/workflows/review-check.yaml
Labels: area: CI, priority: 2 - normal

#531 Advent of Code 2020
  bot/__init__.py
  bot/constants.py
  bot/exts/christmas/advent_of_code/__init__.py
  bot/exts/christmas/advent_of_code/_caches.py
  bot/exts/christmas/advent_of_code/_cog.py
  bot/exts/christmas/advent_of_code/_helpers.py
  bot/exts/christmas/adventofcode.py
  bot/resources/advent_of_code/about.json
Labels: needs core dev approval, priority: 0 - critical, season: christmas
