Repository python-discord/sir-lancebot, pull requests merged in 2020-12, with the labels that each got.

#543 Switch to policy bot for approval status
  .github/review-policy.yml
  .github/workflows/review-check.yaml
Labels: needs 1 approval, needs core dev approval

#542 Use custom status embeds for workflow runs
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
Labels: area: CI, type: feature

#540 Modify error handler check for locally handled errors.
  bot/exts/evergreen/error_handler.py
  bot/exts/evergreen/snakes/_snakes_cog.py
Labels: needs core dev approval, s: waiting for author

#541 Aoc2020
  bot/constants.py
  bot/exts/christmas/advent_of_code/_cog.py
Labels: needs core dev approval

#535 Refactor Advent of Code background tasks to account for deseasonification
  bot/constants.py
  bot/exts/christmas/advent_of_code/_cog.py
  bot/exts/christmas/advent_of_code/_helpers.py
Labels: area: backend, area: frontend, needs core dev approval, priority: 1 - high, season: christmas, type: bug

#547 Sentry SDK version bump, integrations adding and Sentry release workflow
  .github/workflows/build.yaml
  .github/workflows/sentry_release.yaml
  Dockerfile
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/constants.py
Labels: area: CI, area: backend, area: dependencies

#483 Make prideavatar support specifying the image by URL
  bot/exts/pride/pride_avatar.py
Labels: hacktoberfest-accepted, needs 1 approval

#484 Replace OMDB with TMDB
  bot/constants.py
  bot/exts/evergreen/snakes/_snakes_cog.py
Labels: hacktoberfest-accepted, needs 1 approval
