Repository python-discord/sir-lancebot, pull requests merged in 2020-10, with the labels that each got.

#468 Hacktoberfest Stats: Check GitHub user exists before searching for PRs
  bot/exts/halloween/hacktoberstats.py
Labels: priority: 2 - normal, season: halloween, type: bug

#455 Partnerzodiac
  bot/exts/valentines/valentine_zodiac.py
  bot/resources/valentines/zodiac_compatibility.json
  bot/resources/valentines/zodiac_explanation.json
Labels: season: evergreen, type: feature

#473 Emoji Count command(ec)
  bot/exts/evergreen/emoji_count.py
Labels: hacktoberfest-accepted

#469 Source cmd
  bot/constants.py
  bot/exts/evergreen/source.py
Labels: hacktoberfest-accepted

#457 Make minesweeper work on every platform
  bot/exts/evergreen/minesweeper.py
Labels: season: evergreen, type: bug

#481 Add space between dice in roll command
  bot/exts/evergreen/fun.py
Labels: area: frontend, priority: 2 - normal, season: evergreen

#499 Trivia: only fuzzy match messages sent in game channel
  bot/exts/evergreen/trivia_quiz.py
Labels: area: backend, priority: 2 - normal

#503 remove redundant set() in issues.py
  bot/exts/evergreen/issues.py
Labels: needs 2 approvals

#507 Change error message for roll command to use the correct prefix
  bot/exts/evergreen/fun.py
Labels: needs 1 approval, priority: 2 - normal, season: evergreen, type: bug

#508 fix keyerror for hackstats
  bot/exts/halloween/hacktoberstats.py
Labels: needs 1 approval

#479 [Bug] emoji command
  bot/exts/evergreen/emoji_count.py
Labels: hacktoberfest-accepted

#478 Bump 'discord.py' to 1.5.1 and use explicit intents
  Pipfile
  Pipfile.lock
  bot/bot.py
Labels: area: dependencies, priority: 1 - high

#496 Fix candy mini-game to group leader-board scores correctly
  bot/exts/halloween/candy_collection.py
  bot/resources/halloween/candy_collection.json
Labels: priority: 2 - normal, season: halloween, type: bug
