Repository python-discord/sir-lancebot, pull requests merged in 2020-04, with the labels that each got.

#391 Send greeting message on bot start-up
  bot/bot.py
Labels: area: frontend, priority: 2 - normal, season: evergreen, status: needs review, type: feature

#396 APOD and Minesweeper command fixes
  bot/exts/evergreen/error_handler.py
  bot/exts/evergreen/minesweeper.py
  bot/exts/evergreen/space.py
  bot/utils/exceptions.py
Labels: level: 0 - beginner, priority: 2 - normal, season: evergreen, status: needs review, type: bug

#395 Wait until guild ready
  bot/bot.py
  bot/exts/easter/egg_facts.py
  bot/exts/evergreen/branding.py
  bot/exts/halloween/spookysound.py
  bot/exts/pride/pride_facts.py
Labels: area: backend, priority: 2 - normal, status: needs review, type: feature
