Repository python-discord/sir-lancebot, pull requests merged in 2020-03, with the labels that each got.

#366 Strip references to seasonalbot chat
  bot/constants.py
  bot/seasons/easter/__init__.py
  bot/seasons/easter/egg_facts.py
  bot/seasons/evergreen/issues.py
  bot/seasons/halloween/candy_collection.py
  bot/seasons/halloween/halloween_facts.py
  bot/seasons/pride/__init__.py
  bot/seasons/pride/pride_facts.py
  bot/seasons/valentines/be_my_valentine.py
  docker-compose.yml
Labels: area: backend, priority: 1 - high, status: needs review

#361 Added .games command
  bot/constants.py
  bot/seasons/evergreen/game.py
Labels: status: needs review

#368 Add pep8-naming and more pre-commit hooks
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Pipfile
  Pipfile.lock
  README.md
  azure-pipelines.yml
  bot/resources/advent_of_code/about.json
  bot/resources/easter/april_fools_vids.json
  bot/resources/evergreen/game_recs/chrono_trigger.json
  bot/resources/evergreen/game_recs/digimon_world.json
  bot/resources/evergreen/game_recs/doom_2.json
  bot/resources/evergreen/game_recs/skyrim.json
  bot/resources/evergreen/magic8ball.json
  bot/resources/evergreen/trivia_quiz.json
  bot/resources/halloween/candy_collection.json
  bot/resources/halloween/halloweenify.json
  bot/resources/halloween/spooky_rating.json
  bot/resources/pride/anthems.json
  bot/resources/pride/drag_queen_names.json
  bot/resources/pride/facts.json
  bot/resources/snakes/snake_idioms.json
  bot/resources/snakes/snake_names.json
  bot/resources/snakes/special_snakes.json
  bot/resources/valentines/date_ideas.json
  bot/resources/valentines/love_matches.json
  bot/resources/valentines/pickup_lines.json
  bot/resources/valentines/valenstates.json
  bot/resources/valentines/valentine_facts.json
  bot/resources/valentines/zodiac_compatibility.json
  bot/seasons/christmas/adventofcode.py
  bot/seasons/evergreen/bookmark.py
  bot/seasons/evergreen/snakes/snakes_cog.py
  bot/seasons/halloween/hacktoberstats.py
  bot/seasons/valentines/be_my_valentine.py
  tox.ini
Labels: area: CI, area: dependencies, priority: 2 - normal, status: needs review, type: feature

#370 Name the use Python version task
  azure-pipelines.yml
Labels: area: CI, priority: 1 - high, status: needs review, type: bug

#371 Added Python bot help command to SeasonalBot
  bot/__main__.py
  bot/bot.py
  bot/constants.py
  bot/help.py
Labels: priority: 2 - normal, status: needs review, type: feature

#373 Bump Python version to 3.8
  Dockerfile
  Pipfile
  Pipfile.lock
  azure-pipelines.yml
Labels: area: CI, area: dependencies, priority: 2 - normal, status: needs review

#250 Battleships Game
  bot/seasons/evergreen/battleship.py
Labels: season: retro gaming, status: needs review, type: feature

#378 Update contributor doc
  CONTRIBUTING.md
Labels: area: docs, priority: 1 - high, type: feature

#364 Space Cog implementing
  bot/constants.py
  bot/seasons/evergreen/space.py
Labels: level: 0 - beginner, priority: 2 - normal, status: waiting for author, type: feature

#382 Game genre matching fix
  bot/seasons/evergreen/game.py
Labels: priority: 3 - low, season: evergreen, status: needs review
