Repository python-discord/sir-lancebot, pull requests merged in 2021-11, with the labels that each got.

#915 Add a border around the scary bat
  bot/resources/holidays/halloween/bat-clipart.png
Labels: area: frontend, type: enhancement, category: events

#909 Fix challenge cog not working for beta languages
  bot/exts/utilities/challenges.py
Labels: type: bug, area: backend, status: needs review, category: utilities

#858 Add coloredlogs and selective trace loggers
  Dockerfile
  bot/__init__.py
  bot/constants.py
  bot/log.py
  bot/monkey_patches.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
Labels: area: backend, type: enhancement, category: core

#943 Fix Startup Crash Loop
  bot/__init__.py
  bot/__main__.py
  bot/constants.py
  bot/log.py
Labels: type: bug, area: backend, priority: 1 - high

#842 Add color command
  bot/exts/utilities/colour.py
  bot/resources/utilities/ryanzec_colours.json
Labels: type: feature, status: WIP, area: backend, category: utilities

#949 Introduce command changes in the AoC Cog
  bot/exts/events/advent_of_code/_cog.py
  bot/exts/events/advent_of_code/_helpers.py
Labels: type: feature, status: needs review, category: events

#951 Disable File Logging By Default
  bot/constants.py
  bot/log.py
Labels: area: frontend, type: enhancement

#957 Aoc count timestamp
  bot/exts/events/advent_of_code/_cog.py
Labels: area: frontend, status: needs review, type: enhancement
