Repository python-discord/sir-lancebot, pull requests merged in 2022-08, with the labels that each got.

#1078 Fix: .uwu incorrectly transforms emojis in their raw text form
  bot/exts/fun/uwu.py
Labels: type: bug, area: backend, status: needs review, category: fun

#1080 Fix issue with .uwu failing to uwuify embeds in replies
  bot/exts/fun/fun.py
  bot/exts/fun/uwu.py
  bot/utils/messages.py
Labels: type: bug, area: backend, status: needs review, category: fun

#1064 Help command fix, normalize suggestions for unknown commands
  bot/exts/core/error_handler.py
  bot/exts/core/help.py
  bot/utils/commands.py
Labels: area: backend, status: needs review, type: enhancement, category: utilities

#1049 Bookmark enhancements
  bot/exts/core/help.py
  bot/exts/utilities/bookmark.py
Labels: area: frontend, status: needs review, type: enhancement

#1094 Add 1<<15 to the raw intents value
  bot/__main__.py
Labels: area: backend, priority: 1 - high, status: needs review, type: enhancement, category: core
